---
- name: Administrar proceso en CentOS8
  hosts: all
  become: yes
  tasks:
    - name: Detener proceso si est치 en ejecuci칩n
      command: "systemctl stop httpd"
      ignore_errors: yes
      async: 300
      poll: 0
      register: proceso_detenido
      when: proceso_detenido.rc == 0

    - name: Iniciar proceso si no est치 en ejecuci칩n
      command: "systemctl start httpd"
      async: 300
      poll: 0
      register: proceso_iniciado
      when: proceso_iniciado.rc == 0 or proceso_detenido.rc != 0

    - name: Comprobar el estado del proceso
      command: "systemctl is-active httpd"
      register: estado_del_proceso

    - name: Mostrar el estado del proceso
      debug:
        msg: "El estado del proceso es {{ estado_del_proceso.stdout }}"
