---
- name: Configurar tareas cron en CentOS 8
  hosts: all
  become: yes
  tasks:
    - name: Agregar tarea cron
      cron:
        name: "Tarea de ejemplo"
        minute: "0"
        hour: "3"
        job: "/ruta/a/tu/script.sh"

    - name: Eliminar tarea cron anterior
      cron:
        name: "Tarea anterior"
        state: absent

    - name: Reiniciar el servicio cron
      systemd:
        name: crond
        state: restarted

